# Generated by Django 4.0.5 on 2022-06-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_ordercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercode',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
