# Generated by Django 4.0.5 on 2022-06-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderCode',
        ),
    ]
