# Generated by Django 4.0.5 on 2022-06-28 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_per_hour',
            new_name='unit_price',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='interval_in_minutes',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='min_unit',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='multiplicity',
            field=models.CharField(choices=[('H', 'Hour'), ('D', 'Day')], default='H', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='required_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_hotel_booking_time',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
