# Generated by Django 4.0.5 on 2022-06-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_price_per_hour_product_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='min_unit',
        ),
        migrations.AddField(
            model_name='product',
            name='time_unit',
            field=models.CharField(choices=[('H', 'Hour'), ('D', 'Day')], default='H', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='multiplicity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
