# Generated by Django 4.0.5 on 2022-06-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_product_min_unit_product_time_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='multiplicity',
            new_name='max_persons',
        ),
        migrations.RemoveField(
            model_name='product',
            name='interval_in_minutes',
        ),
        migrations.AddField(
            model_name='product',
            name='min_unit',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
