# Generated by Django 4.0.5 on 2022-06-28 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_end_dates_end_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecialInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('common_type', models.CharField(blank=True, choices=[('W', 'Будни'), ('E', 'Выходные')], max_length=1, null=True)),
                ('additional_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_special_intervals', to='api.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Dates',
        ),
    ]
