# Generated by Django 4.0.5 on 2022-06-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_order_record_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_price',
        ),
    ]
