# Generated by Django 4.0.5 on 2022-07-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='persons',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
