# Generated by Django 4.0.5 on 2022-07-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_product_max_hour_product_min_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_unit',
            field=models.PositiveSmallIntegerField(default=8),
            preserve_default=False,
        )
    ]
