# Generated by Django 4.0.5 on 2022-07-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_product_max_unit_alter_product_max_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecialinterval',
            name='common_type',
            field=models.CharField(blank=True, choices=[('E', 'Выходные')], max_length=1, null=True),
        ),
    ]
