# Generated by Django 4.0.5 on 2022-07-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_order_attempts_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='resends_left',
            field=models.SmallIntegerField(default=3),
            preserve_default=False,
        ),
    ]
