# Generated by Django 4.0.6 on 2022-07-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_productfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPushNotificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('push_token', models.CharField(max_length=255)),
            ],
        ),
    ]
