# Generated by Django 4.0.6 on 2022-07-16 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0042_userpushnotificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpushnotificationtoken',
            name='username',
        ),
        migrations.AddField(
            model_name='userpushnotificationtoken',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='push_token', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
