# Generated by Django 4.0.6 on 2022-07-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_persons',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
