# Generated by Django 4.0.6 on 2022-07-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_cart_persons_alter_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecialinterval',
            name='common_type',
        ),
        migrations.AddField(
            model_name='productspecialinterval',
            name='is_weekends',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
