# Generated by Django 4.0.6 on 2022-07-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_remove_productspecialinterval_common_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
