# Generated by Django 4.0.6 on 2022-07-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_productfile_is_primary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfile',
            options={'ordering': ['is_primary']},
        ),
    ]
