# Generated by Django 4.0.6 on 2022-07-29 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_productfile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_persons',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
