# Generated by Django 4.0.6 on 2022-08-02 07:38

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_productfile_file_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=imagekit.models.fields.ProcessedImageField(upload_to='files'),
        ),
    ]
