# Generated by Django 4.0.6 on 2022-08-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_productfile_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecialinterval',
            options={'ordering': ['-is_weekends']},
        ),
    ]
